ImgStoWeb/Controllers/AdminLoginController.cs
using ImgStoWeb.ModelViews;
using ImgStoWeb.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ImgStoWeb.Controllers
{
    public class AdminLoginController : Controller
    {
        public ActionResult Login()
        {
            return View("~/Views/Admin/Login.cshtml");
        }
        [HttpPost]
        public async Task<ActionResult> HandleLogin(User user)
        {
            IGalSvc galSvc = new GalSvc();
            if (await galSvc.AdminLogin(user))
            {
                Session["Admin"] = user.UserId;
            }
            return RedirectToAction("Index","Admin");
        }
    }
}

ImgStoWeb/Views/Admin/CreateCategory.cshtml
@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container-fluid">
    @if (TempData["IsSuccess"] != null)
    {
        if ((bool)TempData["IsSuccess"])
        {
            <h1>Created</h1>
        }
        else
        {
            <h1>Errors</h1>
        }
    }
    <form method="post" action="@Url.Action("HandleCreateCat")">
        <div class="form-group">
            <label for="CatId">Category Id</label>
            <input id="CatId" class="form-control" name="CategoryId" />
        </div>
        <div class="form-group">
            <label for="CatName">Category Name</label>
            <input id="CatName" class="form-control" name="CategoryName" />
        </div>
        <button type="submit" class="btn btn-success">Create</button>
    </form>

    </div>

ImgStoWeb/Views/Admin/CreateImgs.cshtml
@{
    ViewBag.Title = "CreateImgs";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    @if (TempData["IsSuccess"] != null)
    {
        if ((bool)TempData["IsSuccess"])
        {
            <h1>Created</h1>
        }
        else
        {
            <h1>Errors</h1>
        }
    }

    <div class="row">
        <form class="col-md-6" enctype="multipart/form-data" method="post" action="@Url.Action("HandleCreateImg")">
            <div class="form-group">
                <label for="ImgName">Image Name</label>
                <input type="text" id="ImgName" name="ImgName" class="form-control" required />
            </div>
            <div class="form-group">
                <label for="CategoryName">Category</label>
                <select id="CategoryName" name="CategoryName" class="form-control" required>
                    @foreach (string str in ViewBag.Categories)
                        {
                            <option>@str</option>
                        }
                </select>
            </div>
            <div class="form-group">
                <label for="ImgFile">File</label>
                <input type="file" id="ImgFile" required class="form-control" name="postedFile"/>
            </div>
            <button type="submit" class="btn btn-success">Create</button>
        </form>
        <div class="col-md-6">
            <div class="imgBG"></div>
            <div class="d-flex justify-content-center imgContent" id="ImgContent">
            </div>
        </div>
    </div>


    @section styles{
        <style>
            .imgBG {
                position: absolute;
                background-color: #7f8fa6;
                opacity: 0.3;
                width: 90%;
                height: 450px;
            }

            .imgContent {
                position: relative;
                width: 400px;
                height: 400px;
                align-content: center;
                margin-left: 60px;
                margin-top: 20px;
            }
        </style>
    }
    @section scripts{
        <script>
            var img;
            var modal;
            var modalImg;
            var captionText;
            $("document").ready(function () {
                $("#ImgFile").change(function (event) {
                    $("#ImgContent").empty();
                    $(".modal").empty();
                    var currItem = event.target;
                    $(currItem.files).each(function (index, data) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            $("#ImgContent").append(
                                "<img id=\"myImg\" src =\"" + e.target.result + "\" width=\"400px\" height=\"400px\"/>"
                            );
                        }
                        reader.readAsDataURL(data);
                    });
                   
                });

                
            });
            
        </script>
    }
</div>

ImgStoWeb/Views/Admin/CreateSubCat.cshtml
@{
    ViewBag.Title = "CreateSubCat";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    @if (TempData["IsSuccess"] != null)
    {
        if ((bool)TempData["IsSuccess"])
        {
            <h1>Created</h1>
        }
        else
        {
            <h1>Errors</h1>
        }
    }

    <form method="post" action="@Url.Action("HandleSubCat")">
        <label for="Cat">Category</label>
        <select id="Cat" required name="FatherName" class="form-control">
            @foreach (ImgStoWeb.ApiModels.CategoryModel str in ViewBag.Category)
            {
                <option>@str.CategoryName</option>
            }
        </select>
        <div class="form-group">
            <label for="SubId">Sub category id</label>
            <input class="form-control" id="SubId" name="SubId" />
        </div>
        <div class="form-group">
            <label for="SubName">Sub category name</label>
            <input class="form-control" id="SubName" name="SubName" />
        </div>
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>

ImgStoWeb/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Dash board";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <!-- Content Row -->
    <div class="row">


        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Number of user</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.UserCount</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Category</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.CatCount</div>
                        </div>

                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Sub Category</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.SubCount</div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Imgs</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.ImgCount</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-image fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Images</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.PendingCount</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-images fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Images Upload Overview</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pie Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <div class="mt-4 text-center small">
                        <span class="mr-2">
                            <i class="fas fa-circle text-primary"></i> Direct
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-success"></i> Social
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-info"></i> Referral
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

   
</div>
<!-- /.container-fluid -->

ImgStoWeb/Views/Admin/ListCategories.cshtml
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "ListCategories";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model IPagedList<ImgStoWeb.ApiModels.CategoryModel>

<table class="table">
    <thead>
        <tr>
            <td>#</td>
            <td>Category name</td>
            <td>Number of subcategory</td>
        </tr>
    </thead>
    <tbody>
        @{ int i = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>@item.CategoryName</td>
                <td>@item.SubCategoryName.Count()</td>
            </tr>
            i = i + 1;
        }
    </tbody>
</table>
<div>
    <h6>Pages</h6>
    <span>
        <a>
            @Html.PagedListPager(Model, pageNumber => Url.Action("ListImgs", new { pageNumber }))
        </a>
    </span>
</div>

ImgStoWeb/Views/Admin/ListImgs.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ImgStoWeb.ApiModels.ImgModel>
@{
    ViewBag.Title = "ListImgs";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<table class="table">
    <thead>
        <tr>
            <td>#</td>
            <td>Img Name</td>
            <td>Uploaded By</td>
            <td>Uploaded Date</td>
            <td>Views</td>
            <td>Like</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @{ int i = 1;}
        @foreach(var item in Model)
        {
        <tr>
            <td>@i</td>
            <td>@item.ImgName</td>
            <td>@item.UploadBy</td>
            <td>@item.UploadDate</td>
            <td>@item.Views</td>
            <td>@item.LikeCount</td>
            <td>
            <td>
                <img width="200" height="200" src="@item.ImgURL" />
            </td>
        </tr>
            i = i + 1;
        }
    </tbody>
</table>
<div>
    <h6>Pages</h6>
    <span>
        <a>
            @Html.PagedListPager(Model, pageNumber => Url.Action("ListImgs", new { pageNumber }))
        </a>
    </span>
</div>

ImgStoWeb/Views/Admin/ListSub.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ImgStoWeb.ApiModels.CategoryModel>
@{
    ViewBag.Title = "ListSub";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <td>#</td>
            <td>Category name</td>
            <td>Father category</td>
        </tr>
    </thead>
    <tbody>
        @{ int i = 1;}
        @foreach (var item in Model)
        {

            foreach (var sub in item.SubCategoryName)
            {
                <tr>
                    <td>@i</td>
                    <td>@item.CategoryName</td>
                    <td>@sub</td>
                </tr>
                i = i + 1;

            }

        }
    </tbody>
</table>
<div>
    <h6>Pages</h6>
    <span>
        <a>
            @Html.PagedListPager(Model, pageNumber => Url.Action("ListImgs", new { pageNumber }))
        </a>
    </span>
</div>

ImgStoWeb/Views/Admin/Login.cshtml
@{ 
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="@Url.Content("~/Content/")vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="@Url.Content("~/Content/")css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" method="post" action="@Url.Action("HandleLogin","AdminLogin")">
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user" name="UserId" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter User Name ...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="Pwd" id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="@Url.Content("~/Content/")vendor/jquery/jquery.min.js"></script>
    <script src="@Url.Content("~/Content/")vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="@Url.Content("~/Content/")vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="@Url.Content("~/Content/")js/sb-admin-2.min.js"></script>

</body>

</html>

ImgStoWeb/Views/Admin/PendingImgs.cshtml
@{
    ViewBag.Title = "PendingImgs";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    @if(TempData["IsSuccess"]!=null){
        if ((bool)TempData["IsSuccess"])
        {
            <h1>Success</h1>
        }
        else
        {
            <h1>Error</h1>
        }
    }
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Image Name</th>
                <th>Posted By</th>
                <th>Uploaded Date</th>
                <th>Category Name</th>
                <th>Image</th>
                <th></th>
                <th></th>
                <th>Is Duplicate</th>
            </tr>
        </thead>
        <tbody>
            @{ int i = 0;}
            @foreach(ImgStoWeb.ApiModels.ImgModel img in ViewBag.Imgs)
            {
                <tr>
                    <td>@i</td>
                    <td>@img.ImgName</td>
                    <td>@img.UploadBy</td>
                    <td>@img.UploadDate</td>
                    <td>@img.CategoryName</td>
                    <td>
                        <img width="200" height="200" src="@img.ImgURL"/>
                    </td>
                    <td><a href="@Url.Action("ConfirmImg")?imgId=@img.ImgId">Confirm</a></td>
                    <td><a href="@Url.Action("DeleteImg")?imgId=@img.ImgId">Delete</a></td>
                    <td>@Html.Raw(ViewBag.IsDup[i])</td>
                </tr>
                i = i + 1;
            }
        </tbody>
    </table>
</div>